### ISSUE TITLE
Update https-proxy-agent

### ISSUE THREAD

**Issue by chilltemp** [PredixDev/passport-predix-oauth#3]
Please update https-proxy-agent to ^2.1.1 to patch a known vulnerability with one of its dependencies.  https://github.com/TooTallNate/node-https-proxy-agent/issues/37

**Comment by gstroup** [comment]
Thanks for letting us know.  We'll try to get this fix released soon.

**Comment by gstroup** [comment]
Fixed in v0.1.55
